version: "3.9"
services:
  postgres:
    container_name: rating_postgres_db
    image: postgres
    environment:
      POSTGRES_DB: "ratingdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "UltraStrongPassw0rd"
    ports:
      - "48002:5432"
    healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U user -d ratingdb" ]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
        - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
        PGADMIN_DEFAULT_EMAIL: "fedor@mail.com"
        PGADMIN_DEFAULT_PASSWORD: "UltraStrongPassw0rd"
        PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
        - "5050:80"
    restart: unless-stopped
    deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 1G
    networks:
        - postgres
networks:
  postgres:
    driver: bridge
    external: true