server.port=8088
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.gateway.discovery.locator=enabled
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=driver-service-drivers
spring.cloud.gateway.routes[0].uri=lb://DRIVER-SERVICE-CLIENT
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/drivers/**
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/driver_service
spring.cloud.gateway.routes[0].filters[1].name=OriginalUrlFilter
spring.cloud.gateway.routes[1].id=driver-service-cars
spring.cloud.gateway.routes[1].uri=lb://DRIVER-SERVICE-CLIENT
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/cars/**
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/driver_service
spring.cloud.gateway.routes[1].filters[1].name=OriginalUrlFilter
spring.cloud.gateway.routes[2].id=passenger-service
spring.cloud.gateway.routes[2].uri=lb://PASSENGER-SERVICE-CLIENT
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/passengers/**
spring.cloud.gateway.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/passenger_service
spring.cloud.gateway.routes[2].filters[1].name=OriginalUrlFilter
spring.cloud.gateway.routes[3].id=ride-service
spring.cloud.gateway.routes[3].uri=lb://RIDE-SERVICE-CLIENT
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/rides/**
spring.cloud.gateway.routes[3].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[3].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[3].filters[0].args.fallbackUri=forward:/fallback/ride_service
spring.cloud.gateway.routes[3].filters[1].name=OriginalUrlFilter
spring.cloud.gateway.routes[4].id=rating-service
spring.cloud.gateway.routes[4].uri=lb://RATING-SERVICE-CLIENT
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/scores/**
spring.cloud.gateway.routes[4].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.fallbackUri=forward:/fallback/rating_service
spring.cloud.gateway.routes[4].filters[1].name=OriginalUrlFilter
resilience4j.circuitbreaker.instances[0].myCircuitBreaker.slidingWindowSize=15
resilience4j.circuitbreaker.instances[0].myCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances[0].myCircuitBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances[0].myCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances[0].myCircuitBreaker.waitDurationInOpenState=5000
resilience4j.circuitbreaker.instances[0].myCircuitBreaker.failureRateThreshold=20