metricbeat.modules:
  - module: prometheus
    period: 30s
    hosts: ["http://host.docker.internal:8082"]
    metrics_path: "/actuator/prometheus"
    metrics:
      - metricsets: ["collector"]


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]