services:
  cab_eureka_service:
    container_name: eureka-server
    image: eureka_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - services

networks:
  services:
    external: true